### PR TITLE
add collection

### PR DESCRIPTION
**Pull request by ChristianGrieger**

### CODE REVIEW

**Comment by jamesscaur** [comment]
@ChristianGrieger do you mind running this instead?

```bash
cd scripts;
npm install;
node updateCollections.js;
```

That way only the metadata will be saved.

The full collection will still pull from https://github.com/jamesscaur/liteordinals-collections when you're on the site.

**Comment by ChristianGrieger** [comment]
@jamesscaur just noticed how to add the collection and you already merged it :) thank you. When does it get pushed to live server?

**Comment by jamesscaur** [comment]
64F5238F-237D-4756-BB3C-FF2036004280

sorry, looks like there’s an issue with the script or the liteordinals-collections repo. I just merged another PR so I’ll see if it’s a problem with that…

**Comment by ChristianGrieger** [comment]
Thanks :)

**Comment by ChristianGrieger** [comment]
Oh now i see the problem its not on the collection page: https://liteordex.scaur.nz/collections.html

**Comment by jamesscaur** [comment]
Will try fix now

**Pull request closed without merging**
